### ISSUE TITLE
week 03 - day 03 - bringing it all together - final

### ISSUE THREAD

**Issue by hayesch19** [hayesch19/Assignments#11]
# Prove yourself, warrior!

You have grown very quickly to have worked with and master HTML, CSS, JavaScript, and basic programming fundamentals. This will be a test of those skills and ideas that you have gained and a reflection of how far you have come.

For this assignment you will be doing 3 code katas, as well as reproducing a website.

## Objectives

- Show off your problem-solving skills
- Show off HTML, CSS, and JavaScript Skills
- Work with an API to create a responsive website, using only Vanilla JS and modern CSS

## Requirements

- Reproduce this[http://sdg-astro-club.surge.sh] website. The data is live at https://sdg-astro-api.herokuapp.com/index.html.

### Explorer Mode

- [x] Complete these code katas, in JavaScript, and turn them in by making a [gist](https://gist.github.com)
      _ [ ][find the one](https://www.codewars.com/kata/you-only-need-one-beginner)
      _ [ ][use your map](https://www.codewars.com/kata/beginner-lost-without-a-map)
      \_ [ ][filter out the geese](https://www.codewars.com/kata/filter-out-the-geese)

- [x] Reproduce [this site](http://sdg-astro-club.surge.sh) exactly
      _ [ ] Should be 100% responsive
      _ [ ] Should pull from https://sdg-astro-api.herokuapp.com/index.html
      API using JavaScript
      _ [ ] Should display a countdown timer to next astronomical event. This timer should countdown until hitting zero
      _ [ ] The carousel should change automatically every 10 seconds

- [x] All code should be:
      _ [ ] readable properly indented
      _ [ ] variables, class names, and functions should be reasonably named
      _ [ ] proper style guides should be followed
      _ [ ] commented

## Additional Resources

- [MDN](https://developer.mozilla.org/en-US/)
- [this site](http://sdg-astro-club.surge.sh)
- API is here: https://sdg-astro-api.herokuapp.com/index.html.

**Comment by hayesch19** [comment]
You Only Need One
https://gist.github.com/hayesch19/14e695438e3d4a2db5761737d906ef31
Lost Without a Map 
https://gist.github.com/hayesch19/b9ab08fffd56bc90ca7fc35e588a2eb2
Filter out the geese 
https://gist.github.com/hayesch19/45a24d67f94a0f3ecd6d599c445034d0

**Comment by hayesch19** [comment]
https://github.com/hayesch19/astroclub

**Comment by mdewey** [comment]
Some oddities in the code that we can chat about some times, but overall good job.

**Comment by hayesch19** [comment]
Your homework **week 03 - day 03 - bringing it all together - final** was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19d6199fa14f30b194db6d85ef06369fdd985597/giphy-10.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/75)**__
