### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by hayesch19** [hayesch19/Assignments#30]
# Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [x] Portfolio link

## Summary
- [x] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [x] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [ ] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [x] Write where you went college and your degree.
- [ ] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [x] Upload or submit a link to your resume for review.

**Comment by hayesch19** [comment]
[Christopher Hayes Resume.docx](https://github.com/hayesch19/Assignments/files/3623888/Christopher.Hayes.Resume.docx)

**Comment by hayesch19** [comment]
[Christopher Hayes Resume.docx](https://github.com/hayesch19/Assignments/files/3626401/Christopher.Hayes.Resume.docx)

**Comment by hayesch19** [comment]
Updated resume with recommended changes from Brandee.
[Christopher Hayes Resume.docx](https://github.com/hayesch19/Assignments/files/3649695/Christopher.Hayes.Resume.docx)

**Comment by ktrammell95** [comment]
Nice and clean but here are a few things to consider...

First note, check your spelling, you have a couple of errors
![Screen Shot 2019-09-26 at 3 58 30 PM](https://user-images.githubusercontent.com/10440779/65720805-bd684200-e076-11e9-9717-1fbc0800d60a.png)

Maybe think about listing some development projects and details. You are already on 2 pages might as well fill out that second page a bit more to make it feel needed. If you do add them I would say to do it above Experience or directly afterward.
